# Generated by Django 2.0.4 on 2018-04-16 20:58

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(default=None, max_length=100000)),
                ('time_of_conversation', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('longest_user_monologue', models.FloatField(blank=True, default=None, null=True)),
                ('longest_customer_monologue', models.FloatField(blank=True, default=None, null=True)),
                ('user_talk_percentage', models.FloatField(blank=True, default=None, null=True)),
                ('user', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, default=None, null=True), size=None), size=None)),
                ('customer', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, default=None, null=True), size=None), size=None)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='conversation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='waveform_api.Conversation'),
        ),
    ]
