# Generated by Django 2.0.4 on 2018-04-16 22:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waveform_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='customer',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, default=None, null=True), size=2), size=None),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='user',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, default=None, null=True), size=2), size=None),
        ),
    ]
